:: Please do not edit this file. If it does not work for you, fix the issue.
:: A personalized .bat only works for you and once you push it you will annoy everyone else.

nasm -f bin -o kernel.bin src/kernel.asm
move /Y kernel.bin bin
mkisofs -b kernel.bin -no-emul-boot -o iDOS.iso bin/
qemu-system-x86_64 -cdrom iDOS.iso