# Please do not edit this file. If it does not work for you, fix the issue.
# A personalized makefile only works for you and once you push it you will annoy everyone else.

all: build
	qemu-system-x86_64 -cdrom iDOS.iso

build:
	nasm -f bin -o kernel.bin src/kernel.asm
	mv kernel.bin bin/kernel.bin
	mkisofs -b kernel.bin -no-emul-boot -o iDOS.iso bin/
	
clean:
	rm -rvf kernel.bin
	rm -rvf iDOS.iso
